replicaCount: 1

image:
  repository: kofolmarko/stats-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8002
  targetPort: 8002

ingress:
  enabled: true
  host: stats.ob-kavici.si
  path: /

env:
  secrets:
    name: stats-service-secrets

probes:
  liveness:
    path: /health/liveness
    port: 8002
    initialDelaySeconds: 3
    periodSeconds: 120
  readiness:
    path: /health/readiness
    port: 8002
    initialDelaySeconds: 5
    periodSeconds: 3600

metrics:
  path: /metrics
